config/routes.rb
Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq" if defined?(Sidekiq) # monitoring console
  root "bulletins#index"
  resources :bulletins
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bulletin.rb
# == Schema Information
#
# Table name: bulletins
#
#  id          :bigint           not null, primary key
#  description :text
#  price       :decimal(10, 2)
#  title       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Bulletin < ApplicationRecord
  validates :title, :description, :price, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include BasicAuth
end

app/controllers/bulletins_controller.rb
class BulletinsController < ApplicationController
  before_action :set_bulletin, only: %i[edit update destroy show]

  def index
    @bulletins = Bulletin.all
  end

  def new
    @bulletin = Bulletin.new
  end

  def create
    @bulletin = Bulletin.new(bulletin_params)
    if @bulletin.save
      redirect_to @bulletin, notice: 'Объявление успешно создано.'
    else
      render :new
    end
  end

  def edit

  end

  def update
    if @bulletin.update(bulletin_params)
      redirect_to @bulletin
    else
      render 'edit'
    end
  end

  def destroy
    @bulletin.destroy
      redirect_to bulletins_path
  end


  def show
  end

  private

  def set_bulletin
    @bulletin = Bulletin.find(params[:id])
  end

  def bulletin_params
    params.require(:bulletin).permit(:title, :description, :price)
  end
end

app/controllers/concerns/basic_auth.rb
module BasicAuth
  extend ActiveSupport::Concern

  included do
    before_action :require_basic_auth
  end

  private

  def require_basic_auth
    expected_username = ENV.fetch("BASIC_AUTH_USERNAME", nil)
    expected_password = ENV.fetch("BASIC_AUTH_PASSWORD", nil)
    return true if expected_username.blank? || expected_password.blank?

    authenticate_or_request_with_http_basic do |username, password|
      ActiveSupport::SecurityUtils.secure_compare(username, expected_username) & \
        ActiveSupport::SecurityUtils.secure_compare(password, expected_password)
    end
  end
end

app/controllers/home_controller.rb
# Renders the home page.
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bulletins_helper.rb
module BulletinsHelper
end

app/helpers/layout_helper.rb
module LayoutHelper
  # Used to achieve nested layouts without content_for. This helper relies on
  # Rails internals, so beware that it make break with future major versions
  # of Rails. Inspired by http://stackoverflow.com/a/18214036
  #
  # Usage: For example, suppose "child" layout extends "parent" layout.
  # Use <%= yield %> as you would with non-nested layouts, as usual. Then on
  # the very last line of layouts/child.html.erb, include this:
  #
  #     <% parent_layout "parent" %>
  #
  def parent_layout(layout)
    @view_flow.set(:layout, output_buffer) # rubocop:disable Rails/HelperInstanceVariable
    output = render(template: "layouts/#{layout}")
    self.output_buffer = ActionView::OutputBuffer.new(output)
  end
end

app/views/bulletins/_form.html.slim
= form_with model: @bulletin, local: true do |f|
  p
    = f.label :title
    = f.text_field :title
  p
    = f.label :description
    = f.text_area :description
  p
    = f.label :price
    = f.text_field :price

  p= f.submit

app/views/bulletins/edit.html.slim
h1 Edit Post
= render 'bulletins/form'

= link_to 'Cancel', bulletin_path

app/views/bulletins/index.html.slim
p Все объявления

app/views/bulletins/new.html.slim
 = render 'bulletins/form'

app/views/bulletins/show.html.slim
h1
  = @bulletin.title
p
  = @bulletin.description
p
  = @bulletin.price
p

= link_to 'Edit ', edit_bulletin_path(@bulletin)
= link_to 'Delete ', bulletin_path(@bulletin), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}
= link_to 'Home', root_path

app/views/home/index.html.erb
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<%# The "application" layout is the default layout. It extends "base"  %>
<%# to include things like header, footer, and alerts that are common  %>
<%# to most (but not all) views.                                       %>

<main class="container">
  <%= render("shared/flash") %>
  <%= yield %>
</main>

<% parent_layout "base" %>

app/views/layouts/base.html.erb
<%# The "base" layout contains boilerplate common to *all* views. %>

<!DOCTYPE html>
<html>
  <head>
    <!-- Rialto <%= Rails.application.config.version %> (<%= l(Rails.application.config.version_time) %>) -->
    <%= capybara_lockstep if defined?(Capybara::Lockstep) %>
    <title>
      <%= "#{strip_tags(yield(:title))} – " if content_for?(:title) %>
      Rialto
    </title>
    <%# Specifies the default name of home screen bookmark in iOS %>
    <meta name="apple-mobile-web-app-title" content="Rialto">

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= yield(:head) %>  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_flash.html.erb
<%# Notice %>
<% if flash[:notice].present? %>
  <div class="alert alert-success"><%= flash[:notice] %></div>
<% end %>

<%# Alert %>
<% if flash[:alert].present? %>
  <div class="alert alert-danger"><%= flash[:alert] %></div>
<% end %>